### ISSUE TITLE
pipenv update --outdated unconditionally delete Pipfile.lock file

### ISSUE THREAD

**Issue by paradoxxxzero** [pypa/pipenv#1698]
On a clean environment, I get this behavior:
```bash
$ pipenv install
Creating a virtualenv for this project…
Using /usr/bin/python (3.6.4) to create virtualenv…
⠋Already using interpreter /usr/bin/python
Using base prefix '/usr'
New python executable in /[path]/.local/share/virtualenvs/pipenv-zOUKMwd0/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: /[path]/.local/share/virtualenvs/pipenv-zOUKMwd0
Creating a Pipfile for this project…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (625834)!
Installing dependencies from Pipfile.lock (625834)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell
```

```bash
$ pipenv install requests
Installing requests…
Collecting requests
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests)
  Using cached certifi-2018.1.18-py2.py3-none-any.whl
Installing collected packages: idna, urllib3, chardet, certifi, requests
Successfully installed certifi-2018.1.18 chardet-3.0.4 idna-2.6 requests-2.18.4 urllib3-1.22

Adding requests to Pipfile's [packages]…
Pipfile.lock (625834) out of date, updating to (7b8df8)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (7b8df8)!
Installing dependencies from Pipfile.lock (7b8df8)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 5/5 — 00:00:00
To activate this project's virtualenv, run the following:
 $ pipenv shell
```
```bash
$ ls
Pipfile  Pipfile.lock
```

```bash
$ pipenv update --outdated

```

```bash
$ ls
Pipfile
```

```bash
$ pipenv --version
pipenv, version 11.6.1
```

Is it intentional? This seems weird.

**Comment by kennethreitz** [comment]
Thanks for the report!

**Comment by kennethreitz** [comment]
fixed :)

**Comment by wlansu** [comment]
This seems to have returned from the grave. I get the exact same result as paradoxxxzero running the latest pipenv build. I run `pipenv update --outdated` and afterwards my lockfile is gone. I get the same result when I run with the --dry-run flag instead.

**Comment by uranusjr** [comment]
@wlansu Could you help verify whether this only reappears with the latest release (2018.7.1), or in a recent (but not latest) release? This would greatly help us pin down the problem. Thanks in advance. It would be great also if you could open a new issue after clarifying when the regression happened, with more detailed information and steps for reproduction.

**Comment by wlansu** [comment]
@uranusjr It also happend with the pipenv-2018.5.18 release, I updated afterwards and verified that it still happened in the latest release.

I could open a new issue, but I don't have more detailed information than paradoxxxzero already provided, so not sure how useful that would be.

**Comment by wlansu** [comment]
@uranusjr I did not test this in any other versions than 2018.5.18 and 2018.7.1.

**Comment by techalchemy** [comment]
I can't reproduce this currently, so I think we are good now! thanks for the report :)
