### ISSUE TITLE
Interdependent editable packages

### ISSUE THREAD

**Issue by caspervdw** [pypa/pipenv#2068]
First of all, thanks for all the work on this great package!

I am working on a project updating some old packages that are not distributed via PyPI but via our own package index. Using pipenv with our own package index works great. However, in my dev environment, I'd like to install them editable from github, checking out the correct branch. I can do so by calling the `pipenv install -e git+git@github.com:<>/<>.git@<>`, which works fine.

The dependency graph of the relevant packages is as follows:

```
lizard-blockbox==0.30.dev0
  - lizard-ui [required: Any, installed: 4.40]
  - lizard-management-command-runner [required: Any, installed: 0.2.dev0]
    - lizard-ui [required: Any, installed: 4.40]
```

Pipenv version: `'11.10.1.dev4'

------------

##### Expected result

Correct installation of three packages from github.

##### Actual result

Pipenv starts installing `lizard-blockbox`, which has a dependency on `lizard-management-command-runner`. This is not on Pypi and installation fails. 

##### Steps to replicate

Generate the Pipfile as follows (the order is important -- see dependency graph):

```
pipenv --two
pipenv install django==1.8.19
pipenv install -e git+git@github.com:lizardsystem/lizard-ui.git@casper-django18#egg=lizard-ui
pipenv install -e git+git@github.com:lizardsystem/lizard-management-command-runner.git@casper-django18#egg=lizard-management-command-runner
pipenv install -e git+git@github.com:lizardsystem/lizard-blockbox.git@casper-django18#egg=lizard-blockbox
```

Resulting Pipfile
```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django = "==1.8.19"
lizard-ui = {git = "git@github.com:lizardsystem/lizard-ui.git", editable = true, ref = "casper-django18"}
lizard-management-command-runner = {git = "git@github.com:lizardsystem/lizard-management-command-runner.git", editable = true, ref = "casper-django18"}
lizard-blockbox = {git = "git@github.com:lizardsystem/lizard-blockbox.git", editable = true, ref = "casper-django18"}

[dev-packages]

[requires]
python_version = "2.7"
```
Then remove the environment and install again: `pipenv --rm`; `pipenv --two`; `pipenv install`.

The following pip error is logged:

```
Looking in indexes: https://pypi.python.org/simple00
Obtaining lizard-blockbox from git+git@github.com:lizardsystem/lizard-blockbox.git@a85e3d9c417df52dbfb8c05ada7a7915f55aa3a5#egg=lizard-blockbox
  Skipping because already up-to-date.
Requirement already satisfied: Django<1.9,>=1.7 in ./.venv/lib/python2.7/site-packages (from lizard-blockbox) (1.8.19)
Requirement already satisfied: django-celery in ./.venv/lib/python2.7/site-packages (from lizard-blockbox) (3.2.2)
Collecting lizard-management-command-runner (from lizard-blockbox)

  Could not find a version that satisfies the requirement lizard-management-command-runner (from lizard-blockbox) (from versions: )
No matching distribution found for lizard-management-command-runner (from lizard-blockbox)
```
##### Proposed fix

A `nodeps=True` option in the Pipfile

**Comment by techalchemy** [comment]
Just don't install them in editable mode, it's the same thing

**Comment by caspervdw** [comment]
That was fast! Thanks. Setting `editable = false` gives me precisely the same issue (after removing env and lockfile)

**Comment by caspervdw** [comment]
Please reopen! @techalchemy

**Comment by caspervdw** [comment]
I found the issue, I misnamed the `egg`, the dashes should have been replaced with underscores. This is solved.

**Comment by caspervdw** [comment]
@techalchemy Please ignore my previous comment. I would like to reopen this issue, it keeps popping up at random. If I deploy the specified Pipfile.lock (well, with different branch names now) sometimes it fails, sometimes it does not.

The issue is that `lizard-blockbox` depends on the other two editable packages. These are not available on PyPI, so if Pipenv happens to install `lizard-blockbox` first, it fails, but if it had installed the other to already, there is no issue. Luckily pipenv retries failed installs, but for 3 interdependent packages, this is not always sufficient.

Best solution would be to “blacklist” other specified VCS packages when installing a VCS package. But pip does not provide this option.

It seems to be a use case for the `sequential` install option; but how would I determine the installation order then?

Other solution might be (bit hacky) convincing pip that VCS dependencies already exist before installing (and then `force-reinstall` at the actual `pip install`.

Now I just retry deployment until it does not fail. Mostly it works on the second try.

**Comment by techalchemy** [comment]
Sequential installs are installed... welll... sequentially. There is a fix for VCS. Installs in the pipeline. Pr is up.

**Comment by caspervdw** [comment]
@techalchemy  Right, that fix for VCS ordering would help indeed, so the order is determined by the Pipfile. Thanks.

**Comment by cwill747** [comment]
@techalchemy this is still failing for me. 

My Pipfile: 

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
"com.example.a" = {ref = "master", git = "https://<private>.git", editable = true, subdirectory = "a"}
"com.example.b" = {ref = "master", git = "https://<private>.git", editable = true, subdirectory = "b"}
"com.example.b" = {ref = "master", git = "https://<private>.git", editable = true, subdirectory = "c"}

[dev-packages]


[requires]
python_version = "2.7"
```

This gives me 

```
> pipenv install
Creating a virtualenv for this project...
Pipfile: <snip>/Pipfile
Using /usr/local/bin/python2.7 (2.7.15) to create virtualenv...
⠋Running virtualenv with interpreter /usr/local/bin/python2.7
New python executable in /Users/<snip>/.local/share/<snip>/<snip>/bin/python2.7
Also creating executable in /Users/<snip>/.local/share/virtualenvs/<snip>/bin/python
Installing setuptools, pip, wheel...done.
Setting project for <snip> to <snip>

Virtualenv location: <snip>
Pipfile.lock (f8f229) out of date, updating to (cfb2eb)...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...

CRITICAL:notpip._internal.index:Could not find a version that satisfies the requirement com.example.a>=1.0.9 (from com.example.b->-r /var/folders/4k/zb_bkrkx5pvgnhsvfz59mw100000gn/T/pipenv-GWr0N2-requirements/pipenv-GQQKDK-constraints.txt (line 15)) (from versions: )
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
No matching distribution found for com.example.a>=1.0.9 (from com.example.b->-r /var/folders/4k/zb_bkrkx5pvgnhsvfz59mw100000gn/T/pipenv-GWr0N2-requirements/pipenv-GQQKDK-constraints.txt (line 15))

/usr/local/lib/python2.7/site-packages/pipenv/_compat.py:113: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/var/folders/4k/zb_bkrkx5pvgnhsvfz59mw100000gn/T/pipenv-nsR755-requirements'>
  warnings.warn(warn_message, ResourceWarning)
```

**Comment by cwill747** [comment]
Note that this works in pip, if you use `dependency_links` like so:
```
setup(
  name="com.example.b",
  version="1.0.0",
  install_requires = [ "com.example.a==1.0.0"],
  dependency_links = [ "git+ssh://git@<snip>#egg=com.example.a&subdirectory=a" ]
)```
`pip install -e /path/to/monorepo/b`

This correctly installs `com.example.a`, but pipenv throws the same error as above
