### ISSUE TITLE
Fatal dependency resolution issue with editable dependencies

### ISSUE THREAD

**Issue by jkp** [pypa/pipenv#2446]
Checkout the code [here](https://github.com/jkp/pipenv-bugs/tree/3ac9854eb785737c0648d072f600ec72406524d2) and run `test.sh` with the latest version of `pipenv` to repro.  Dependencies fail to resolve. If you revert to `2018.5.18` it works.

Additional info: moving the same sub-dependencies into the `Pipfile` directly also allows `pipenv` to resolve things properly (see the previous commit in the tree).

**Comment by andreeagherman** [comment]
We had a similar issue:

We are using a private editable repo declared like: 
`
{git = "git@github.com:compnay/library-name.git@version", editable=true}`

Tried to change it to:
`{ref = "version" git= "git@github.com/company/library-name", editable=true}`

Pipenv still added `ssh://` in front of it and then failed with an `InstallationError`:
```bash
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "git clone -q ssh://git@github.com/company/library-name
```

Reverting to 2018.5.18 fixed the issue.

**Comment by techalchemy** [comment]
` {git = "git@github.com:compnay/library-name.git@version", editable=true}` => ` {git = "git@github.com:compnay/library-name.git", editable = true, ref = "version"}

There is supposed to be an SSH in front of he URI here, If you're not sure how to build a pipfile entry by hand please use the CLI to add your entry.

@jkp your pipfile says:

```
"lib1" = {editable = true, path = "lib1"}
"lib2" = {editable = true, path = "lib2"}
"22dede5" = {path = "./lib1", editable = true}
"2a0dbdb" = {path = "./lib2", editable = true}
```

You are installing the same package 2 times each.  Is there a reason why?

For the record, I cloned your repository and did have a resolution issue.  I then did as you suggested and put the dependencies from the sub-packages directly into the Pipfile:

```ini
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
notebook = "<5.5.0"
tensorflow = "*"

[requires]
python_version = "3.6"
```

Which caused the exact same resolution issue as I was already experiencing:

```console
Virtualenv location: /home/hawk/.virtualenvs/pipenv-bugs-qLoyEUKf
Locking [dev-packages] dependencies...
Locking [packages] dependencies...

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,==0.9999999,>=0.99999999pre
Tried: 1.0-reupload, 0.2, 0.9, 0.10, 0.11, 0.11.1, 0.90, 0.95, 0.99, 0.999, 0.9999, 0.99999, 0.999999, 0.9999999, 0.99999999, 0.999999999, 0.999999999, 1.0.1, 1.0.1
Skipped pre-versions: 1.0b1, 1.0b2, 1.0b3, 1.0b5, 1.0b6, 1.0b7, 1.0b8, 1.0b9, 1.0b10, 1.0b10
There are incompatible versions in the resolved dependencies.
```

So it looks to me like there is a legitimate conflict.  I double checked, and the version of tensorboard this installs does pin a lower version of html5lib than it's dependency `bleach` installs.  Newer versions of tensorboard don't pin html5lib at all.

**Comment by jkp** [comment]
The double entries are an accident :)  Strange you got the conflict...I did not...see the first commit in the repo.  How is that possible?

**Comment by jkp** [comment]
I believe this issue should be reopened - I've paired down the test-case even more now - it is reproducable on two different machines for now.

Please checkout [this commit](https://github.com/jkp/pipenv-bugs/tree/4310a247f8e17624e633dcf90a8adf62495f22ba) and run `test.sh`

**Comment by tcwalther** [comment]
@jkp I just ran this on my own machine, and can confirm that it passes with `pipenv==2018.5.18` and fails with `pipenv==2018.6.25`.

**Comment by Diggsey** [comment]
@techalchemy that's not correct - I can confirm that `pipenv==2018.6.25` also broke our pipfile, and not only that but *there is no solution that works under the new version of pipenv for private repos*.

Adding an `ssh://` in front does not work. We've had to roll back to the previous version.

This is a recurring problem - pipenv regularly breaks installations from private repos on upgrades. Please add tests that cover this case before releasing new versions.

**Comment by tcwalther** [comment]
@techalchemy I'd love to keep this discussion focused on the bug report. I don't know whether there is a history with previous bug reports that were filed in a non-constructive way, and if so, I really understand your pain. It is clear that everyone on this project is a volunteer, and you are perfectly right, people coming to this issue tracker shouldn't just complain about things being broken.

At the same time, there are various ways to commit to a project. Making a pull request with a working solution to a problem is definitely the strongest way to commit, but the barrier of entry for outsiders for a significantly complicated project such as pipenv is very high. Another way to contribute is to provide a simple test case to narrow down the problem, which the author of this bug, @jkp, has done.

You may find his `test.sh` script unnecessary; I personally very much enjoyed it - I used his example code to verify that the bug can be reproduced on my machine as well, and then commented in this thread to confirm that I can reproduce it. I have seen enough cases where a reported bug could not be reproduced on a different machine because of one person's weird local machine configuration that I've come to value independent verifications of a bug a lot.

If all of this sounds reasonable to you, I'd be very grateful if you reopened the ticket. Please don't hesitate to ask for further information or other test cases if it helps in narrowing down the issue - I'm hopeful that this way, we can split the workload in debugging this, and ultimately help on improving what is already a fantastic package manager for Python.

**Comment by jkp** [comment]
Hi again

I appreciate that I have not fixed the issue but I did manage to add [an integration test](https://github.com/jkp/pipenv/commit/7bb1099269eb62c7dade9ab4238572fb90e4ea78) that reproduces the issue within the `pipenv` codebase.  The problem seems to be related to the version constraints on `html5lib` in the `bleach` library.  Since `pipenv` can install and lock `bleach==1.5.0` without the first command being run first, my expectation is that `pipenv` should be able to build a working dependency tree with the code shown - I would expect it to essentially uninstall the first version (`2.1.3`) and replace it with `1.5.0` (which it does) and build a dependency tree from there.  It seems to fail somewhere on that journey.

Hopefully this will help if someone has the time and knowledge to try to track down this problem.

**Comment by mattijohn** [comment]
@techalchemy I don't think you are correct that there should be a `ssh://` in front of the URI. Looking at the comment in https://github.com/pypa/pipenv/blob/d47b43002a5674a005e1d5d152b687baec590326/pipenv/patched/notpip/_internal/vcs/git.py#L270 it looks like `ssh://` doesn't work with GitHub.

Running on my own machine I get the following error:

`pipenv.patched.notpip._internal.exceptions.InstallationError: Command "git clone -q ssh://git@github.com:private/repo.git /var/folders/m_/g7w0_d3512zch868x39xpm3r0000gn/T/tmp0mpnu3epsource/repo" failed with error code 128 in None`

Executing the `git clone` command in the terminal results in this error: `ssh: Could not resolve hostname github.com:private: nodename nor servname provided, or not known`. However, executing the `git clone` without `ssh://` works fine.

I haven't had time to come up with a fix but if nobody else picks it up I'd be happy to contribute later this week.

**Comment by uranusjr** [comment]
`ssh://` totally works with GitHub. The problem is that we are using the wrong format; it should be `ssh://git@github.com/private/repo.git` instead.

The problem likely lies into how requirementslib converts the URL before passing it into Git. We need to convert the `git@host:username/repo.git` format into `ssh://git@host/username/repo.git` so we can correctly parse it with `urllib.parse` to get relevent URL information. I hope this helps you tracking down the problem

**Comment by mattijohn** [comment]
Thanks @uranusjr, you're right it's the `git@host:username/repo.git` format that doesn't work with `ssh://`. I think the `get_url_rev` function needs to be changed to change the format if it adds `ssh://`. 

In the meantime users can workaround this in the latest version of pipenv by changing the URI in their Pipfile.

**Comment by jkp** [comment]
Folks, I think we're discussing two separate issues here.  The issue I posted and have created a test-case for doesn't relate to `ssh://` urls.  Maybe migrate that discussion to a new issue so we can keep this one focussed?

**Comment by techalchemy** [comment]
Indeed. Not to mention that issue is already fixed and released.

**Comment by jkp** [comment]
@techalchemy which thing do you say is fixed?

**Comment by mattijohn** [comment]
@jkp apologies, I saw the second message in this thread matched my issue and assumed your issue was the same thing.

@techalchemy the problem with prefixing URI's containing ':` instead of `/` isn't fixed in the latest release: I'm using version `2018.7.1`, freshly installed this morning. I think a new issue needs to be created for the URI format bug.

**Comment by techalchemy** [comment]
The `ssh://` issue. I just saw that you have a test case in here — I haven’t looked at that yet but I’ll reopen now and take a look in a bit

**Comment by techalchemy** [comment]
@mattijohn if you have a problem and it isn’t about the specific thing being discussed please go fill out the issue template in a new issue with a reproducible test case.

**Comment by tcwalther** [comment]
@techalchemy This issue still persists with the current version 51cbc2e2f76a7c60f879a608fd96e95faca35f2e. It can be reproduced using @jkp's [example code](https://github.com/jkp/pipenv-bugs/tree/3ac9854eb785737c0648d072f600ec72406524d2) that he linked to in the bug description.

It would be great if you could re-open this issue.

**Comment by lovepocky** [comment]
this issue still exists in version `2018.11.26`

**Comment by festum** [comment]
The issue still there with version `2018.11.26` cmd `pipenv install -e git+ssh://git@private.repo:7999/org/repo.git#egg=repo`.
