### ISSUE TITLE
pipenv 2018.11.14 fails with "Not a valid python version" when installed via pip on a system that has Python 2.7

### ISSUE THREAD

**Issue by massenz** [pypa/pipenv#3294]
### Issue description

When I run this:
`pipenv --python 3.6 install`

it fails even if both `python3` and `python3.6` are on the `PATH`:

```
└─( which python
/usr/bin/python

└─( which python3
/usr/bin/python3

└─( python3 --version
Python 3.6.7

└─( which python3.6
/usr/bin/python3.6
```

### Expected result

`pipenv` should be sufficiently smart to figure it out by itself that `python3.6` is the desired binary.

### Actual result

This is the error, full stacktrace at the bottom:
```
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/models/python.py", line 366, in parse
    raise ValueError("Not a valid python version: %r" % version)
ValueError: Not a valid python version: <LegacyVersion('2.7.15+')>
```

### Steps to replicate

See below.

-------------------------------------------------------------------------------

Please run `$ pipenv --support`, and paste the results here.

    $ pipenv --support | xclip

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.11.14'`

Pipenv location: `'/usr/local/lib/python2.7/dist-packages/pipenv'`

Python location: `'/usr/bin/python'`

Python installations found:
</details>

(and, LoL - `--support` fails with the same error)

-------------------------------------------------------------------------------
### Full Stacktrace
```
└─( pipenv --python 3.6 install
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli/command.py", line 203, in cli
    clear=state.clear,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 569, in ensure_project
    pypi_mirror=pypi_mirror,
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 489, in ensure_virtualenv
    python = ensure_python(three=three, python=python)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 397, in ensure_python
    path_to_python = find_a_system_python(python)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 360, in find_a_system_python
    python_entry = finder.find_python_version(line)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/backports/functools_lru_cache.py", line 137, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/pythonfinder.py", line 114, in find_python_version
    major=major, minor=minor, patch=patch, pre=pre, dev=dev, arch=arch, name=name
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/models/path.py", line 396, in find_python_version
    ver = next(iter(self.get_pythons(sub_finder)), None)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/models/path.py", line 279, in get_pythons
    reverse=True
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/models/path.py", line 277, in <genexpr>
    (p for p in self._filter_paths(finder) if p.is_python),
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/models/path.py", line 264, in <genexpr>
    pth for pth in unnest(finder(p) for p in self.path_entries if p is not None)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/utils.py", line 138, in unnest
    for el in target:
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/models/path.py", line 264, in <genexpr>
    pth for pth in unnest(finder(p) for p in self.path_entries if p is not None)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/models/mixins.py", line 121, in find_python_version
    for child in unnest(self.pythons.values())
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/models/path.py", line 523, in pythons
    for path, entry in self.children.items():
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/models/path.py", line 494, in children
    for child_key, child_val in self._gen_children():
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/models/path.py", line 487, in _gen_children
    yield (child.as_posix(), PathEntry.create(path=child, **pass_args))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/models/path.py", line 567, in create
    _new = cls(**creation_args)
  File "<attrs generated init a309dc529103f000f3a8248fa1855f93d8af58ae>", line 16, in __init__
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/models/path.py", line 510, in get_py_version
    py_version = PythonVersion.from_path(path=self, name=self.name)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/models/python.py", line 418, in from_path
    instance_dict = cls.parse(py_version.strip())
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/pythonfinder/models/python.py", line 366, in parse
    raise ValueError("Not a valid python version: %r" % version)
ValueError: Not a valid python version: <LegacyVersion('2.7.15+')>
```

**Comment by jxltom** [comment]
It looks like ```<LegacyVersion('2.7.15+')``` is not successfully parsed by ```pythonfinder```

**Comment by jxltom** [comment]
Oh, I think it is duplicated with https://github.com/pypa/pipenv/issues/3241 which is already fixed in #3254. Could you try the latest master branch of pipenv? That should solve your problem.

**Comment by techalchemy** [comment]
I'll have the last bugfix before the release up and building, but yeah, this is another pythonfinder issue unfortunately -- it's fixed in master but not released yet.

I'm going to close this for now (you'll be able to fix by upgrading in a few hours), sorry for the trouble!

P.S. You should avoid using `sudo pip <x>` at all costs if possible, it's a good way to really mess your system up -- ubuntu and most other distributions repackage most python packages as they have system level dependencies on those packages.  For example, `apt` requires specific python components to be fully functional, and you can definitely mess those up by using `sudo pip install` -- consider using `pyenv` or at the very least using `--user` to manage the separation

**Comment by massenz** [comment]
Hey - super-thanks for jumping on this one so quickly, appreciated!

Absolutely no trouble, I'll update my version once it's ready.

> You should avoid using sudo pip <x> at all costs if possible, it's a good way to really mess your system up

No kidding! I'm always super-careful with the system distro, which is why is have been using virtualenv and now pipenv; unfortunately, it's a bit of a catch-22: in order to use either, they need to be installed on the system python; I only upgrade (manually, via `pip`) only `pip` itself, `virtualenv` and (now) `pipenv` -- everything else, it's `apt-get` all the way down.

**Comment by Wyzzard123** [comment]
Facing this problem 2 years later on a windows computer. First it told me that Anaconda3 wasn't a valid python path. Then I installed Anaconda and it told me that 2.7 wasn't a valid python path.

What finally worked for me was massenz's solution to just install the older version of pipenv: 
`pip install pipenv==2018.10.13`

**Comment by mrhyun** [comment]
Using pip install pipenv==2018.10.13 like Wyzzard123 mentioned fixed the problem for me. I was stuck in Anaconda3 not being a vlid python path before

**Comment by jg185366** [comment]
I'm still encountering this issue on `pipenv-2021.5.29`. Installing the version mentioned above fixed my issue.
