### ISSUE TITLE
pipenv install ignores install_requires from setup.py 

### ISSUE THREAD

**Issue by svenhartmann** [pypa/pipenv#4355]
Affacted release: `2020.6.2`

works fine in `2018.11.26`

### Issue description

`pipenv install` does not install dependencies from setup.py -> `install_requires`

Pipefile 

    example-adapter = {ref = "my-tag", git = "ssh://git@myinternalgit/example-adapter.git"}

setup.py:

	setup(
		name="example-adapter",
		version="1.7.1",
		author="abc",
		author_email="abc",
		description=("abc"),
		long_description=read('README.md'),
		keywords=["abc", "adapter"],
		packages=find_packages(),
		python_requires='>=3.6',
		install_requires=['python-jose==3.1.0', 'cachetools==3.1.0'],
		tests_require=[]
	)

### Expected result

Configured packages from `example-adapter/setup.py` / `install_requires` are being installed.

### Actual result

Configured packages from `example-adapter/setup.py` / `install_requires` NOT are being installed.

### Steps to replicate

pipenv install

**Comment by CloudySnake** [comment]
We are also seeing the same thing.  We have a library that installs from a GitHub repo, and the dependencies for the library do not install with pipenv 2020.6.2

**Comment by cbrochtrup** [comment]
This can be reproduced by install the following Pipfile and checking if joblib, a dependency of Librosa, is installed.

```
[[source]]
url = 'https://pypi.python.org/simple'
verify_ssl = true
name = 'pypi'

[requires]

[packages]
librosa = {ref = "5d7314fa226355f96bdfb50a8a60282570cf5917",git = "git://github.com/librosa/librosa.git"}
```

Run the following with pipenv versions `2018.11.26` and `2020.6.2` and joblib will only be found in the former.
```shell
$ pipenv install
$ find $(pipenv --venv) -name 'joblib'
```

**Comment by pmahoney** [comment]
Same issue is present in 2020.5.28

**Comment by adam-grant-hendry** [comment]
Perhaps use `pipenv-setup` (https://pypi.org/project/pipenv-setup/). Also, seems like a historical issue #1263 .

**Comment by frostming** [comment]
Did you regenerate the lock file? Or can you show the lockfile content?

**Comment by svenhartmann** [comment]
The dependencies are still missing within the lock file.

**Comment by jordivandooren** [comment]
Setting environment variable `PIPENV_RESOLVE_VCS` to 0 fixed this exact problem for me (newer Pipenv versions skipping subdependencies).

 [Quote](https://pipenv.pypa.io/en/latest/advanced/#configuration-with-environment-variables):

> PIPENV_RESOLVE_VCS
    Tells Pipenv whether to resolve all VCS dependencies in full.
    As of Pipenv 2018.11.26, only editable VCS dependencies were resolved in full. To retain this behavior and avoid handling any conflicts that arise from the new approach, you may set this to ‘0’, ‘off’, or ‘false’.

**Comment by ms-lolo** [comment]
We're still experiencing this issue in the latest `2020.11.15` version of `pipenv` and we've been stuck in the 2018 version because of it. We use local editable installs heavily and dependencies in our `setup.py` files are simply being ignored.

**Comment by ms-lolo** [comment]
seems this is not happening to me in `2020-11-4` so I files a new ticket in hopes that it is a simple regression.

**Comment by zjpiazza** [comment]
I am experiencing this issue as well. Has there been any updates on this?

**Comment by konstantinmiller** [comment]
Make sure `setuptools` is installed before you run `pipenv install -e .`

That is, run `pip install --upgrade setuptools` prior to running `pipenv install -e .`

**Comment by ms-lolo** [comment]
@konstantinmiller that doesn't seem possible. the local `.` dependency is defined in `Pipfile` and the venv doesn't exist until you first run `pipenv install`. We don't have a point in time, after the venv is created but before pipenv installs dependencies, where we can upgrade setuptools.

**Comment by danetrata** [comment]
Seems there has been a regression. I needed to define `PIPENV_RESOLVE_VCS=0` in my `Dockerfile` to recognize or install dependencies again.

Required packages missing from `Pipfile.lock`

Target package `setup.py`
```
(cloudsense-logging) danetrata@danetrata-ubuntu:~/gitlab/ulap/cloudsense/cloudsense-logging$ cat setup.py 
from setuptools import setup, find_packages

from pipenv.project import Project
from pipenv.utils import convert_deps_to_pip

pfile = Project(chdir=False).parsed_pipfile
requirements = convert_deps_to_pip(pfile["packages"], r=False)

setup(
    name="cloudsense-logging",
    version="0.1.0",
    packages=find_packages(),
    install_requires=requirements,
)
```

**Comment by matteius** [comment]
Please recheck with `pipenv=2022.8.17`
